### PR TITLE
Made github based build closer to jenkins and disable tests

### PR DESCRIPTION
**Pull request by iloveeclipse**
Fixes issue #25

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@vogella : the build seem to be green now.

However, I still wonder if we only should run compile & API check on github, and leave the rest for jenkins? I see the benefit in faster feedback loop to the developer - sometimes we have to wait ~40 minutes just to get a message that version was not updated.

Or why should we run tests two times?

**Comment by laeubi** [comment]
@iloveeclipse I find it good to have a fast feedback-loop.

We could even have a label use to also run tests in special circumstanes only e.g.

`if: ${{ github.event.label.name == 'Run GH Tests' }}`

this is very usefull if eclipse infra is down and GH action is the only possible verification...

**Comment by iloveeclipse** [comment]
@laeubi : if you know how to do that conditional full build, feel free to take it over.

All: is that now a common understanding, that we would like a quick compile/API check here and not all tests *by default*, and the full tests will be done in jenkins?

If yes, I would update the file to disable tests.

**Comment by mickaelistria** [comment]
> All: is that now a common understanding, that we would like a quick compile/API check here and not all tests by default, and the full tests will be done in jenkins?

To be honest, on all projects where I've seen multiple CI builds, I always use the Jenkins one as the reference and the only one to really care about, and other ones are more intermediary information. Sometimes the "quicker" build is helpful as it notice some errors earlier/faster, but usually it's useless as it isn't sufficient in order to merge things, and the jenkins build is still the blocking one.

**Comment by iloveeclipse** [comment]
OK I will remove the tests.

**Comment by iloveeclipse** [comment]
Hmm, adding "skipTests" doesn't run API check. Is there any trick to have no tests but API check only?
```
[1258](https://github.com/eclipse-platform/eclipse.platform.resources/runs/5777353830?check_suite_focus=true#step:5:1258)
[INFO] --- maven-antrun-plugin:3.0.0:run (check-skip-api-analysis) @ org.eclipse.core.tests.resources.saveparticipant ---
[INFO] Skipping Antrun execution
```

**Comment by mickaelistria** [comment]
> adding "skipTests" doesn't run API check

That's not intended and is a bug/limitation. The parent pom would need to be changed so skipTests doesn't influence API check.

**Comment by iloveeclipse** [comment]
> The parent pom would need to be changed so skipTests doesn't influence API check.
@mickaelistria : I'm not a maven user at all. I would merge this PR now, could you apply the change you mean in extra PR?

**Comment by mickaelistria** [comment]
> could you apply the change you mean in extra PR?

I cannot commit to complete it shortly, but I can try to look at it ASAP. Can you please open an issue against eclipse.platform.releng.aggregator that describes the problem so we'll use it to track the necessary changes?

**Comment by laeubi** [comment]
@iloveeclipse @mickaelistria anyone knows where this bot message came from? This really spams my mailbox and it does not even includes if the build is successful or not ...

**Comment by iloveeclipse** [comment]
@laeubi : which exact bot message produced how much spam? I've force pushed last commit few times, because of various yaml syntax issues / argument changes, so that wasn't the bot.

**Comment by laeubi** [comment]
See https://github.com/eclipse-platform/eclipse.platform.resources/pull/27#issuecomment-1085053942 this might not be related to your change but seems some new feature...

**Comment by iloveeclipse** [comment]
That is not a bug, it's a feature. But two mails isn't spam???

**Comment by jukzi** [comment]
that message  is from https://github.com/eclipse-platform/eclipse.platform.resources/pull/11

**Comment by laeubi** [comment]
> That is not a bug, it's a feature. But two mails isn't spam???

And I don't like that featue :-1:  for yesterday I got seven additional mails from the `releng-bot` each PR already generates at least two mails (create+merge) now it increases by 25% with `releng-bot`, and the consequence will be that I most probably will disable notifications at all for eclipse repositories I got 219 mails yesterday so yes this *is* spammin my mailbox ...

**Comment by iloveeclipse** [comment]
That is interesting, I only got two extra bot mails, but I'm subscribed to all platform too. So why do you receive so much bot mails?

**Comment by laeubi** [comment]
You can disable notification except for those you are participating or mentioned, maybe because of that? Anyways I dont find the message usefull, as it does not state anything about the build result.

**Comment by jukzi** [comment]
+1 needs status or for fails only. (i used to highlight failed built messages and did not care about success)

**Comment by vogella** [comment]
IMHO we should get of Jenkins from the foundation of GH builds are faster.
Or if sometimes GH or Jenkins is faster lets leave both so that we get at
least one result fast

Christoph Läubrich ***@***.***> schrieb am Do., 31. März
2022, 19:20:

**Pull request merged**
