### PR TITLE
Revert "Improve IFile.getLineSeparator() API"

### PR DESCRIPTION
**Pull request by jukzi**
Reverts eclipse-platform/eclipse.platform.resources#159

### CODE REVIEW

**Comment by mickaelistria** [comment]
Jorg, I'll revert that. And please don't re-revert. You quick agreement on some bad API with another committer is not sufficient to make the API acceptable. Following existing patterns and OO principles is more important.

**Comment by jukzi** [comment]
> Jorg, I'll revert that. And please don't re-revert. You quick agreement on some bad API with another committer is not sufficient to make the API acceptable. Following existing patterns and OO principles is more important.

Mickael, the same to you. you will follow the princibles of eclipse please that every commiter has the same power and you had been outvoted.

**Comment by mickaelistria** [comment]
> Mickael, the same to you. you will follow the principles of eclipse please that every commiter has the same power and you had been outvoted.

I was not outvoted on https://github.com/eclipse-platform/eclipse.platform.resources/pull/159 , you're the only one who argued against it. I didn't bring it publicly to other project leads aa I thought that you would have the capacity to understand there are OO patterns and practices to follow for sustainable API, and I hope you already understand how important and difficult API maintenance can be to follow those patterns over just starting a new way to doing. Sure, it's annoying to get some work you've done reverted or reworked, but we've all gone through that and please show the maturity of accepting it graciously instead of interpreting it like an aggression.

**Comment by akurtakov** [comment]
Reverting patches is not the way to get things done. If committers disagree - discussion happens at the Project Leads level. If there is still disagreement issue should be brought to the PMC and every committer incl. project leads have to play by that decision.
After the procedural guidelines, let's go to some technical such: This commit missed the point why the revert happens entirely. It's been documented at https://github.com/eclipse-platform/.github/wiki/PMC-project-guidelines#commit-messages and reiterated last week via https://www.eclipse.org/lists/eclipse-dev/msg12031.html . 
Please make sure to behave accordingly!!!

**Comment by akurtakov** [comment]
For the PMC: See also https://github.com/eclipse-platform/eclipse.platform.resources/pull/161 .

**Comment by akurtakov** [comment]
After discussing at the PMC today we went to writing short "committer disagreement resolution" section for cases like this one. See at https://github.com/eclipse-platform/.github/wiki/PMC-project-guidelines#committer-disagreement-resolution  , it's  shortened version of https://www.eclipse.org/projects/dev_process/ .
There are few issues here:
* Revert without an obvious reason - from PMC POV there is no clear explanation why exactly this revert happens. Without clear arguments no dispute can be won. 
* Project Lead have to step up and resolve disputes and **clearly say** he acts as such in case people are not aware of hierarchy. Please state it every time you have to and point to the guidelines so everyone is aware.

Please follow these rules in the future to prevent cases like this one.

**Pull request merged**
