### PR TITLE
Add a comment to the PR from Jenkins when build is finished

### PR DESCRIPTION
**Pull request by jonahgraham**
Post a comment to PR when build is complete.

Use the github-pipeline plug-in to do so. Documented:
https://github.com/jenkinsci/pipeline-github-plugin

### CODE REVIEW

**Comment by jonahgraham** [comment]
This is an experiment to figure out if we can use pipeline-github-plugin to achieve https://github.com/eclipse-platform/eclipse.platform.resources/pull/4#issuecomment-1079420463

At the moment it looks like pipeline-github-plugin is not enabled for the platform CI instance

**Comment by merks** [comment]
This is cool!

**Comment by jonahgraham** [comment]
I have added a simple comment (see https://github.com/eclipse-platform/eclipse.platform.resources/pull/11#issuecomment-1084924837) at the end of the build.

I now leave it for others to enhance as they see fit.

Because of GitHub actions vs Jenkins PR build I don't want to invest more time on writing better Jenkins pipelines if we are just going to abandon it in favour of GitHub actions.

**Comment by akurtakov** [comment]
FYI, We can not fully move to GH actions as only Jenkins have write access to download.eclipse.org. I understand this doesn't matter for verification builds but putting it here so everyone is aware of this limitation.

**Comment by jukzi** [comment]
that message is like spam because i get an email after each build. Together with the feature that any push does triggger builds of all open PRs i get spammed by email. see
https://github.com/eclipse-platform/eclipse.platform.resources/pull/4
for example.

**Comment by laeubi** [comment]
> that message is like spam because i get an email after each build.

Yep, same here, that's really annoying. If it would be a message that he build *failed* it probably would be useful, but thats something that should be send to the author/reviewers of a PR only....

**Pull request merged**
