### PR TITLE
Improve IFile.getLineSeparator() API

### PR DESCRIPTION
**Pull request by mickaelistria**
Previous proposal used wrong OO and discoverability patterns and are
inconsistent with other similar methods (IFile.getEncoding(), IFile.getCharset()...),
so better align with those.

### CODE REVIEW

**Review by jukzi — DISMISSED** [review]
-2.
A Helper method instead of an interface method is better because it allows null argument. We can use null argument for a IDE wide definition what should happen outside the workspace.
Also getEncoding() and getLineSeparator() do target the same subject an are also in the UI always grouped together.
Also the Helper method gives easy access to project/workspace setting which are not IFile.
It's also bad practice to have an interface method which is supposed to have exactly a single implementation.

**Comment by jukzi** [comment]
> IFile.getEncoding(), IFile.getCharset()...),
getEncoding is deprecated, and there is already getEncoding() in ResourcesPlugin

**Comment by jukzi** [comment]
> Having null references across the code is although harmful

see  https://github.com/eclipse-platform/eclipse.platform.team/pull/23 for another example where also null is used in the argument which could be unified with a helper method.

IFile.getCharset() is defined to throw CoreException in multiple cases. That is  inadequate.

**Comment by jukzi** [comment]
> `file` is not null here, otherwise a NPE happens in previous lines.

I have not deeply checked all those copy&paste implementation. most of them do have a null check, no matter if it is actually used or not. Another example org.eclipse.pde.internal.core.AbstractModel.fixLineDelimiter(String, IFile) which explicitly mentions null too in the javadoc. Is it actually used with null? i do not know.

> Do we need that? 

Querying a project or folder would make sense if one wants to generate a batch of files.

**Comment by mickaelistria** [comment]
> Querying a project or folder would make sense if one wants to generate a batch of files.

Do we have use case for it now? For charset, containers have a getDefaultCharset() that we could mimic. But if it's not proven useful yet, I suggest we do not add it now and maybe do it later when we have user stories to back it.

**Comment by jukzi** [comment]
We provide an API for others too. I know a bunch of code on third party that does writes batches and think it's more handy to have a single all purpose method then to have a lot of different methods which again end up in copy&paste code to determine which one to select.

**Pull request merged**
